version: '3.8'

services:
  backend:
    container_name: codetogether-backend
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    container_name: codetogether-redis
    image: redis:7
    ports:
      - '6379:6379'
    restart: always
