version: '3.8'

services:
  redis:
    image: redis
    container_name: codetogether-redis
    ports:
      - '6379:6379'
    restart: always

  backend:
    container_name: codetogether-backend
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
